
export const SET_MOBILE_NUMBER = 'SET_MOBILE_NUMBER';
export const SET_LOGIN_RESPONSE = 'SET_LOGIN_RESPONSE';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_EMPLYERLOGIN_RESPONSE='SET_EMPLYERLOGIN_RESPONSE'
export const SET_CHAT_TO_COMPANY='SET_CHAT_TO_COMPANY';
export const SET_COMPANY_DATA='SET_COMPANY_DATA';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_MESSAGES = 'SET_MESSAGES';